os: unstable
image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

install:
  - choco install opencv -version 3.4.0
  
before_build:
  - SET ARCH=x64
  - SET APP_PATH=%CD%
  - IF EXIST C:\tools\OpenCV* CD C:\tools*
  - SET OPENCV_ROOT_PATH=%CD%\opencv
  - CD %APP_PATH%
  - SET OPENCV_DIR=%OPENCV_ROOT_PATH%\build\%ARCH%\vc14
  - SET QTDIR=C:\Qt\5.7\msvc2015_64

build_script:
  - cd build
  - echo %OPENCV_DIR%
  - echo %QTDIR%
  - ps: $file = "$pwd\deploy.zip"
  - ps: (new-object System.Net.WebClient).Downloadfile("https://github.com/livecv/live-pm/archive/master.zip", $file)
  - ps: 7z x -y $file -o"."
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - mv live-pm-master/* .
  - python --version
  - python livepm/main.py build .. msvc2015_64
  - python livepm/main.py deploy .. msvc2015_64
  - dir

artifacts:
  - path: 'build\livecv-*.zip'
    name: Release

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'View Changelog.md for further details.'
  provider: GitHub
  auth_token:
    secure: 'ewCMPMl6d/IVBZ0r/ZApqeh0NgF/0UMMtKTqvQcmTNFb3uK57XFyqbZBHLDICAVC'
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true    
    
    
