#include "linecontrol.h"
#include "qmath.h"
#include "textedit_p.h"
#include <QQmlProperty>
#include <queue>

namespace lv {

std::function<bool(LineControl::LineSection, LineControl::LineSection)>
    LineControl::LineSection::compare = [](LineSection a, LineSection b)->bool {
        return a.position < b.position;
    };

std::function<bool(LineControl::LineSection, LineControl::LineSection)>
    LineControl::LineSection::compareVisible = [](LineSection a, LineSection b)->bool {
        return a.visiblePosition < b.visiblePosition;
    };

std::function<bool(LineControl::LineSection, LineControl::LineSection)>
    LineControl::LineSection::compareBounds = [](LineSection a, LineSection b)->bool {
        return a.startPos < b.startPos;
    };

LineControl::LineControl(QObject *parent) :
          QObject(parent)
        , m_blockHeight(0)
        , m_dirtyPos(0)
        , m_prevLineNumber(0)
        , m_lineNumber(0)
        , m_maxWidth(0)
{
    if (!parent) m_textEdit = new TextEdit(nullptr, true);
    else m_textEdit = static_cast<TextEdit*>(parent);

    QObject::connect(m_textEdit, &TextEdit::lineCountChanged, this, &LineControl::lineCountChanged);
}

/**
 * \brief Adds a line section which starts at line `pos`, ending on line `pos + num`.
 * This section's `visibleRange` is 1 (third parameter in the constructor),
 * because the only visible line is the first one.
 * \returns Offset generated by the insertion operation
 */
int LineControl::addCollapse(int pos, int num)
{
    LineSection ls(pos, num + 1, 1, LineSection::Collapsed);

    if (m_textEdit &&
        m_textEdit->code() &&
        m_textEdit->code()->textDocument()){

        auto doc = m_textEdit->code()->textDocument();

        ls.startPos = doc->findBlockByNumber(pos).position();
        ls.endPos = doc->findBlockByNumber(pos + num).position() + doc->findBlockByNumber(pos + num).length() - 1;
    }

    return addLineSection(ls);
}

/**
 * \brief Removes `Collapsed` line section at given position
 * \returns Offset generated by the removal operation
 */
int LineControl::removeCollapse(int pos)
{
    return removeLineSection(LineSection(pos, 0, 0, LineSection::Collapsed), false);
}


/**
 * \brief Adds a palette given by its position `pos`, the number of lines of code it's replacing
 * given by `span`, its item `p`, as well as start and end position of the code that it's replacing.
 * If it's a "fake palette", i.e. a `Fragment` used to hide lines of code at the beginning and the
 * end of the viewport, its height is 0.
 */
void LineControl::addPalette(int pos, int span, QQuickItem *p, int startPos, int endPos)
{   
    LineSection ls;
    ls.position = pos;
    ls.range = span;
    ls.type = static_cast<int>(p->height()) == 0 ? LineSection::Fragment : LineSection::Palette;
    ls.palette = p;
    ls.visibleRange = qCeil((p->height() > 0 ? p->height() + 10 : 0)*1.0/ m_blockHeight);

    ls.width = static_cast<int>(p->width());
    ls.startPos = startPos;
    ls.endPos = endPos;

    addLineSection(ls);

    emit refreshAfterPaletteChange(pos+span-1, ls.rangeOffset());
}

/**
 * \brief This function reacts to an external resize of the palette height.
 * This potentially creates offset which needs to be applied to all
 * sections after it
 */
void LineControl::resizePaletteHeight(QQuickItem *p)
{
    auto it = m_sections.begin();
    for (; it != m_sections.end(); ++it)
        if (it->type == LineSection::Palette && it->palette == p) break;

    if (it == m_sections.end()) return;

    int newVisibleRange = qCeil((p->height() > 0 ? p->height() + 10 : 0)*1.0/ m_blockHeight);
    int delta = newVisibleRange - it->visibleRange;

    if (delta != 0)
    {
        unsigned index = static_cast<unsigned>(it - m_sections.begin());
        offsetAfterIndex(index, delta, false);
        it->visibleRange = newVisibleRange;
        emit refreshAfterPaletteChange(it->position + it->range - 1, delta);
    }
}

/**
 * @brief In the event of a palette changing its width, we simply
 * update it in the appropriate line section, as well as reset the
 * maximum width of the space needed to display the total content in the editor
 */
void LineControl::resizePaletteWidth(QQuickItem *p)
{
    auto it = m_sections.begin();
    for (; it != m_sections.end(); ++it)
        if (it->type == LineSection::Palette && it->palette == p) break;

    if (it == m_sections.end()) return;

    it->width = static_cast<int>(p->width());

    // update the max width
    auto max = 0;
    for (auto it = m_sections.begin(); it != m_sections.end(); ++it)
    {
        if (it->width > max) max = it->width;
    }

    m_maxWidth = max;
}


/**
 * \brief Removes a given palette from the sections, optionally destroying it as well if
 * the flag `destroy` is set to true.
 */
void LineControl::removePalette(QQuickItem *p, bool destroy)
{
    unsigned i = 0;
    for (; i < m_sections.size(); ++i)
        if (m_sections[i].type == LineSection::Palette
         && m_sections[i].palette == p)
            break;

    if (i == m_sections.size()) return;
    int pos = m_sections[i].position;
    int range = m_sections[i].range;
    int delta = m_sections[i].rangeOffset();

    removeLineSection(m_sections[i], destroy);

    // reevaluate max width
    auto max = 0;
    for (auto it = m_sections.begin(); it != m_sections.end(); ++it)
    {
        if (it->width > max) max = it->width;
    }

    m_maxWidth = max;

    emit refreshAfterPaletteChange(pos + range - 1, -delta);
}

/**
 * \brief Sets the block height to a given value. Since this is the basic unit
 * of measurement in `LineControl` (i.e. everything is measured in lines),
 * we have to recalculate the heights of palettes in terms of number of lines, since their
 * size doesn't scale in the same way.
 */
void LineControl::setBlockHeight(int bh)
{
    m_blockHeight = bh;

    for (unsigned i = 0; i < m_sections.size(); ++i)
    {
        if (m_sections[i].type == LineSection::Collapsed) continue;

        int newVisibleRange = qCeil((m_sections[i].palette->height() > 0 ? m_sections[i].palette->height() + 10 : 0)*1.0/ m_blockHeight);
        if (newVisibleRange != m_sections[i].visibleRange)
        {
            offsetAfterIndex(i, newVisibleRange - m_sections[i].visibleRange, false);
            m_sections[i].visibleRange = newVisibleRange;
        }
    }
}

void LineControl::reset()
{
    m_prevLineNumber = m_lineNumber;
    m_lineNumber = 0;
    m_dirtyPos = -1;
    m_sections.clear();
}

std::vector<LineControl::LineSection> LineControl::sections()
{
    return m_sections;
}

/**
 * \brief Main listener for changes in the text document.
 * Calls appropriate handlers in case text was either removed or added.
 */
void LineControl::contentsChange(int pos, int removed, int added)
{
    if (m_sections.empty()) return;

    if (removed > 0)
        codeRemovalHandler(pos, removed);

    if (added > 0)
        codeAddingHandler(pos, added);
}

/**
 * \brief Returns the vertical offset needed when drawing the node for the given
 * blockNumber, or the cursor in that block. It's given in pixels instead of lines.
 *
 */
int LineControl::pixelDrawingOffset(int blockNumber, bool forCursor)
{
    int offset = 0;
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(),
        LineSection(blockNumber, 0, 0, LineSection::Collapsed), LineSection::compare);
    if (upper != m_sections.begin() && !m_sections.empty())
    {
        auto current = std::prev(upper);

        // The current section is the first one that's not above the given block number, which means
        // that blockNumber >= current->position.
        if (current->type == LineSection::Collapsed && blockNumber == current->position)
        {
            // If the line we're drawing is the collapsed one, the offset is the
            // difference between its visiblePosition and actual position
            offset = current->positionOffset();
        }
        else if (blockNumber < current->position + current->range && !forCursor)
        {
            // If the blockNumber is inside a "hidden" part of the section,
            // we need to draw it "outside" of the viewport, which is done
            // by offsetting it in the negative direction
            offset = -blockNumber - 2;
        }
        else if (blockNumber >= current->position + current->range)
        {
            // The drawing offset in this case is given by the position offset of the
            // section itself, as well as the offset that it creates on its own
            offset = current->positionOffset() + current->rangeOffset();
        }
    }
    return offset * m_blockHeight;
}

/**
 * \brief Transforms a clicked visible position inside the viewport
 * into a transposed, "fake" click position that corresponds to the actual
 * block number if there were no sections present
 */
int LineControl::transposeClickedPosition(int y)
{
    int visibleBlockClicked = y / m_blockHeight;
    int resultBlock = visibleBlockClicked;

    LineSection search;
    search.visiblePosition = visibleBlockClicked;

    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(),
        search, LineSection::compareVisible);

    if (upper != m_sections.begin() && !m_sections.empty()) {
        auto prev = std::prev(upper);

        if (upper == m_sections.end() && prev->type == LineSection::Fragment
            && prev->position != 0)
        {
            resultBlock = prev->position - 1;
        }
        else if (visibleBlockClicked >= prev->visiblePosition + prev->visibleRange)
        {
            resultBlock = visibleBlockClicked - prev->positionOffset() - prev->rangeOffset();
        }
        else if (prev->type == LineSection::Collapsed && visibleBlockClicked == prev->visiblePosition)
        {
            resultBlock = prev->position;
        } else
        {
            resultBlock = prev->position - 1;
        }
    }

    return resultBlock * m_blockHeight + m_blockHeight / 2;
}

/**
 * \brief Total offset generated by sections, necessary for
 * calculations of actual dimensions of the entire canvas
 */
int LineControl::totalOffset()
{
    if (m_sections.empty()) return 0;
    auto lastSection = m_sections[m_sections.size()-1];
    return lastSection.positionOffset() + lastSection.rangeOffset();
}

/**
 * \brief Taking into consideration the offsets before a given visible line,
 * we calculate which absolute line of text it represents
 */
int LineControl::visibleLineToAbsoluteLine(int visible)
{
    LineSection ls;
    ls.visiblePosition = visible;
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(), ls, LineSection::compareVisible);

    int abs = visible;
    if (upper != m_sections.begin())
    {
        auto prev = std::prev(upper);
        if (visible >= prev->visiblePosition + prev->visibleRange)
            abs = visible - prev->positionOffset() - prev->rangeOffset();
        else if (prev->type == LineSection::Collapsed && visible == prev->visiblePosition)
            abs = prev->position;
        else abs = -1; // not mapping to an absolute line
    }

    if (abs >= m_textEdit->code()->textDocument()->blockCount()) return -1;
    return abs;
}

bool LineControl::isHiddenByPalette(int blockNumber)
{
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(), LineSection(blockNumber, 0, 0, LineSection::Palette), LineSection::compare);
    if (upper != m_sections.begin() && !m_sections.empty())
    {
        auto prev = std::prev(upper);
        if (prev->type == LineSection::Palette
                && blockNumber < prev->position + prev->range)
            return true;
    }
    return false;
}

bool LineControl::isHiddenByCollapse(int blockNumber)
{
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(), LineSection(blockNumber, 0, 0, LineSection::Palette), LineSection::compare);
    if (upper != m_sections.begin() && !m_sections.empty())
    {
        auto prev = std::prev(upper);
        if (prev->type == LineSection::Collapsed
                && blockNumber < prev->position + prev->range
                && blockNumber != prev->position)
            return true;
    }
    return false;
}

bool LineControl::isFirstLineOfCollapse(int blockNumber)
{
    auto lower = std::lower_bound(
        m_sections.begin(), m_sections.end(),
        LineSection(blockNumber, 0,0,LineSection::Collapsed),
        LineSection::compare);
    if (lower == m_sections.end() || lower->type != LineSection::Collapsed)
        return false;

    return lower->position == blockNumber;
}

/**
 * \brief If we're moving the cursor through text, it needs to skip hidden lines.
 * We calculate the necessary forward skip in this function
 */
int LineControl::offsetToNextVisibleLine(int blockNumber)
{
    auto lower = std::lower_bound(
        m_sections.begin(), m_sections.end(),
        LineSection(blockNumber, 0,0,LineSection::Collapsed),
        LineSection::compare);
    if (lower != m_sections.end())
    {
        switch (lower->type)
        {
        case LineSection::Palette:
            if (blockNumber + 1 == lower->position)
                return lower->range;
            break;
        case LineSection::Collapsed:
            if (blockNumber == lower->position)
                return lower->range - 1;
            break;
        case LineSection::Fragment:
            if (blockNumber + 1 == lower->position)
                return -1;
            break;
        }
    }

    return 0;
}

/**
 * \brief If we're moving the cursor through text, it needs to skip hidden lines.
 * We calculate the necessary backwards skip in this function
 */
int LineControl::offsetToPreviousVisibleLine(int blockNumber)
{
    auto upper = std::upper_bound(
        m_sections.begin(), m_sections.end(),
        LineSection(blockNumber, 0,0,LineSection::Collapsed),
        LineSection::compare);
    if (upper != m_sections.begin() && !m_sections.empty())
    {
        auto prev = std::prev(upper);
        if (blockNumber == prev->position + prev->range)
        switch (prev->type)
        {
        case LineSection::Palette:      return prev->range;
        case LineSection::Collapsed:    return prev->range - 1;
        case LineSection::Fragment:     return -1;
        }
    }

    return 0;
}


/**
 * \brief Sets the line where there was any change, be it a collapse,
 * palette or text modification, so everything after it is potentially in
 * a wrong state
 */
void LineControl::setDirtyPos(int dirtyPos)
{
    m_dirtyPos = dirtyPos;
}

/**
 * \brief Line count change listener which wraps a function that
 * handles such changes, and emits another, more detailed signal that a change has happened
 */
void LineControl::lineCountChanged()
{
    m_prevLineNumber = m_lineNumber;
    m_lineNumber = m_textEdit->code()->textDocument()->blockCount();
    if (m_prevLineNumber == m_lineNumber) return;

    int delta = m_lineNumber - m_prevLineNumber;
    bool internal = false;

    handleLineChange(delta, internal);

    emit lineDelta(delta, m_dirtyPos, internal);

}

unsigned LineControl::insertIntoSorted(LineControl::LineSection ls)
{
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(), ls, LineSection::compare);
    unsigned position = static_cast<unsigned>(upper - m_sections.begin());
    m_sections.insert(upper, ls);
    return position;
}

void LineControl::calculateVisiblePosition(unsigned pos)
{
    int off = 0;
    for (unsigned i = 0; i < pos; ++i)
        off += m_sections[i].rangeOffset();
    m_sections[pos].visiblePosition = m_sections[pos].position + off;
}

/**
 * \brief Applies the given offset to every section and sub-section that
 * is positioned after the given index. Optionally, it moves their positions,
 * as well as their visible positions, depending on the context.
 */
void LineControl::offsetAfterIndex(unsigned index, int offset, bool offsetPositions, bool offsetVisible)
{
    std::queue<LineSection*> q;
    for (unsigned i = index + 1; i < m_sections.size(); ++i)
    {
        q.push(&m_sections[i]);
        while (!q.empty())
        {
            LineSection* lsp = q.front(); q.pop();
            for (int x = 0; x < lsp->nested.size(); ++x)
                q.push(&lsp->nested[x]);

            if (offsetVisible) lsp->visiblePosition += offset;
            if (offsetPositions) lsp->position += offset;
            if (lsp->type == LineSection::Palette)
            {
                // Positions the palette in the center of its designated space.
                lsp->palette->setY(lsp->visiblePosition * m_blockHeight + (lsp->visibleRange * m_blockHeight - lsp->palette->height()) / 2 + 6);
            }
            else if (lsp->type == LineSection::Fragment)
            {
                // Managing the ending boundary of end fragment
                lsp->range = m_lineNumber - lsp->position;
            }
        }
    }
}

/**
 * \brief For code that was removed between positions `pos` and `pos+removed`,
 * we need to remove the appropriate sections that were deleted as well,
 * and also shift everything after accordingly.
 */
void LineControl::codeRemovalHandler(int pos, int removed)
{
    LineSection search;

    // Find sections which need to be shifted only.
    search.startPos = pos + removed;
    auto safe = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);

    // Find sections that were affected by the code removal.
    search.startPos = pos;
    auto iter = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);

    bool internal = false;
    if (iter != m_sections.begin())
    {
        iter = std::prev(iter);

        if (iter->startPos <= pos && pos + removed <= iter->endPos)
        {
            internal = true;
            // handling the case when removed text is inside a section (isn't reflected in the visible part of text)

            LineSection* parent = &(*iter);
            while (parent)
            {
                int leftIndex = -1, rightIndex = -1;
                LineSection *newParent = nullptr;
                while (true)
                {
                    // finding which nested sections contain the left and right borders of the removed text
                    for (int i = 0; i < parent->nested.size(); ++i)
                    {
                        if (pos >= parent->nested[i].startPos && pos < parent->nested[i].endPos)
                            leftIndex = i;
                        if (pos + removed >= parent->nested[i].startPos && pos + removed < parent->nested[i].endPos)
                            rightIndex = i;
                    }

                    if (leftIndex == -1 && rightIndex == -1) break;
                    // if it's the same section that contains both,
                    // this means the nesting goes even deeper, so
                    // we continue the process with the nested sub-section
                    if (leftIndex == rightIndex)
                    {
                        newParent = &parent->nested[leftIndex];
                        break;
                    }

                    // The removal of code means that the sections contained are also being
                    // "destabilized" i.e. erasing a part of a collapsed section expands it, which
                    // pops out its nested sections. This is done for both affected sections
                    if (leftIndex != -1)
                        for (auto sec: parent->nested[leftIndex].nested)
                            parent->nested.push_back(sec);
                    if (rightIndex != -1)
                        for (auto sec: parent->nested[rightIndex].nested)
                            parent->nested.push_back(sec);

                    int offset = 0;
                    // The newly expanded sections are also removed
                    if (leftIndex != -1)
                    {
                        parent->nested.erase(parent->nested.begin() + leftIndex);
                        offset = -1;
                    }
                    if (rightIndex != -1)
                        parent->nested.erase(parent->nested.begin() + rightIndex + offset);



                    leftIndex = -1;
                    rightIndex = -1;
                }

                // we shift the appropriate positions of sections that are after
                // the last affected position
                for (unsigned i = 0; i < parent->nested.size(); ++i){
                    if (parent->nested[i].startPos > pos + removed)
                    {
                        parent->nested[i].startPos -= removed;
                        parent->nested[i].endPos -= removed;
                    }
                }

                parent->endPos -= removed;

                // if we've reached the end of descending through the hieararchy of sections,
                // this means that we only need to remove the sections contained between
                // the boundaries of removed text, since there's no other affected sections anymore
                if (newParent == nullptr)
                {
                    for (auto it = parent->nested.begin(); it != parent->nested.end();)
                    {
                        if (pos < it->startPos && it->endPos < pos + removed)
                            it = parent->nested.erase(it);
                        else ++it;
                    }
                }

                // going deeper into the nesting, or ending the loop
                parent = newParent;
            }
        }
    }

    if (!internal)
    {
        // If the code removed wasn't contained in a single section,
        // it potentially affects multiple first-level sections.

        // Handle left boundary
        while (true)
        {
            search.startPos = pos;
            auto iter = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);
            if (iter != m_sections.begin())
            {
                iter = std::prev(iter);
            }
            else break; // no section that contains left boundary anymore

            if (iter->type == LineSection::Fragment) break;
            if (iter->startPos < pos && pos < iter->endPos)
            {
                if (iter->palette)
                {
                    removePalette(iter->palette);
                } else {
                    // This might pop out several nested collapses,
                    // which is why we have an infinite loop
                    int position = iter->position;
                    int delta = removeCollapse(iter->position);
                    signalRefreshAfterCollapseChange(position, delta);
                }
            } else break;
        }

        // Handle the right boundary in a way similar to the one above
        while (true)
        {
            search.startPos = pos + removed;
            auto iter = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);
            if (iter != m_sections.begin())
            {
                iter = std::prev(iter);
            }
            else break; // no section that contains right boundary anymore

            if (iter->type == LineSection::Fragment) break;
            if (iter->startPos < pos + removed && pos + removed < iter->endPos)
            {
                if (iter->palette)
                {
                    removePalette(iter->palette);
                } else {
                    int pos = iter->position;
                    int delta = removeCollapse(pos);
                    signalRefreshAfterCollapseChange(pos, delta);
                }
            } else break;
        }

        // now we should delete all sections between
        while (true)
        {
            search.startPos = pos;
            iter = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);

            if (iter != m_sections.end() && iter->startPos < pos + removed)
            {
                if (iter->palette)
                {
                    removePalette(iter->palette);
                } else {
                    int pos = iter->position;
                    int delta = removeCollapse(pos);
                    signalRefreshAfterCollapseChange(pos, delta);
                }

            }
            else break;
        }

        search.startPos = pos + removed;
        safe = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);
    }

    // We update the boundaries of sections which are positioned after the removed code
    // TODO: This should probably consider their nested sections as well.
    for (auto it = safe; it != m_sections.end(); ++it)
    {
        it->startPos -= removed;
        it->endPos -= removed;
    }

}

/**
 * \brief The case of adding code after a given position, which is
 * the task of this function, is simpler, in the sense that nothing
 * is being destroyed, merely shifted
 */
void LineControl::codeAddingHandler(int pos, int added)
{
    std::queue<LineSection*> q;

    LineSection search;
    search.startPos = pos;
    auto iter = std::upper_bound(m_sections.begin(), m_sections.end(), search, LineControl::LineSection::compareBounds);

    if (iter != m_sections.begin() && !m_sections.empty())
    {
        iter = std::prev(iter);
    }


    // For every section, nested or otherwise, that was positioned after the text insertion point,
    // we need to shift the appropriate section bounds by the amount of added characters
    while (iter != m_sections.end())
    {
        q.push(&(*iter));
        ++iter;
    }

    while (!q.empty())
    {
        LineSection* lsp = q.front(); q.pop();
        for (int x = 0; x < lsp->nested.size(); ++x)
            q.push(&lsp->nested[x]);

        // If the section contains the text addition point, we shift the round bound only
        if (lsp->startPos <= pos && pos < lsp->endPos)
            lsp->endPos += added;

        // If the sections is after the text addition point, we shift both bounds
        if (lsp->startPos > pos)
        {
            lsp->startPos += added;
            lsp->endPos += added;
        }

        if (lsp->type == LineSection::Fragment && lsp->position != 0) // handles end fragment bounds
        {
            lsp->endPos = m_textEdit->code()->textDocument()->characterCount() -1;
        }
    }
}


bool LineControl::handleOffsetsWithinASection(int index, int delta)
{
    // the lines added/removed are contained inside a single section
    LineSection& sec = m_sections[index];

    std::queue<LineSection*> q;
    q.push(&sec);
    // For each nested section, and even sections nested any level deeper, we need to move
    // the line boundaries. If the change happened inside the section, we only offset the right boundary.
    // If the section is position after the change location, we move both boundaries.
    while (!q.empty())
    {
        LineSection* lsp = q.front(); q.pop();
        for (int x = 0; x < lsp->nested.size(); ++x)
            q.push(&lsp->nested[x]);

        if (lsp->position <= m_dirtyPos && m_dirtyPos < lsp->position + lsp->range)
            lsp->range += delta;
        if (lsp->position > m_dirtyPos)
        {
            lsp->position += delta;
            lsp->visiblePosition += delta;
        }

        if (lsp->type == LineSection::Palette)
        {
            // Considering the new, shifted position of a palette, we place it in the center of its designated spaces
            lsp->palette->setY(lsp->visiblePosition * m_blockHeight + (lsp->visibleRange * m_blockHeight - lsp->palette->height()) / 2 + 6);
        }
        else if (lsp->type == LineSection::Fragment && lsp->position != 0)
        {
            // We modify the ending boundary of the end fragment
            lsp->range = m_lineNumber - lsp->position;
        }
    }
    return true;
}

/**
 * \brief Starting from `m_dirtyPos`, this function handles a line change of `delta` lines,
 * either added or removed. If the line change happened inside a hidden part of code,
 * i.e. inside a section, we need to handle this change internally. We also have to offset
 * every section that follows after it.
 */
void LineControl::handleLineChange(int delta, bool& internal)
{
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(), LineSection(m_dirtyPos, 0,0,LineSection::Collapsed), LineSection::compare);

    if (upper != m_sections.begin() && !m_sections.empty())
    {
        auto prev = std::prev(upper);
        if (m_dirtyPos < prev->position + prev->range)
        {
            internal = handleOffsetsWithinASection(prev-m_sections.begin(), delta);
        }
    }

    offsetAfterIndex(static_cast<unsigned>(upper-m_sections.begin() -1), delta, true, !internal);
}

int LineControl::firstContentLine()
{
    if (m_sections.empty()) return 0;
    auto first = m_sections[0];
    if (first.type == LineSection::Fragment && first.position == 0)
        return first.range;
    return 0;
}

int LineControl::lastContentLine()
{
    int blockCount = m_textEdit->code()->textDocument()->blockCount();
    if (m_sections.empty()) return blockCount;
    auto last = m_sections[m_sections.size()-1];
    if (last.type == LineSection::Fragment && last.position + last.range == blockCount)
        return last.position;
    return blockCount;
}

/**
 * \brief Returns the first visible line of text before the given one
 */
int LineControl::firstVisibleLineBefore(int lineNumber)
{
    auto upper = std::upper_bound(m_sections.begin(), m_sections.end(),
        LineSection(lineNumber, 0, 0, LineSection::Collapsed), LineSection::compare);

    if (upper != m_sections.begin())
    {
        auto prev = std::prev(upper);
        int currResult = lineNumber;
        while (true)
        {
            switch (prev->type)
            {
            case LineSection::Collapsed:
                if (currResult > prev->position && currResult < prev->position + prev->range)
                {
                    return prev->position;
                }
                return currResult;
            case LineSection::Palette:
            case LineSection::Fragment:
                // In case here are multiple palettes/fragments in a row,
                // we have to jump back for each of them.
                // TODO: The functions `offsetToNextVisibleLine` and `offsetToPreviousVisibleLine`
                // should probably do this in the same manner, making this function unecessary.
                if (currResult >= prev->position && currResult < prev->position + prev->range)
                {
                    currResult = prev->position - 1;

                    if (prev == m_sections.begin())
                    {
                        return currResult;
                    }
                    prev = std::prev(prev);
                } else
                {
                    return currResult;
                }
                break;
            }
        }

    }

    return lineNumber;
}

void LineControl::signalRefreshAfterCollapseChange(int pos, int delta)
{
    emit refreshAfterCollapseChange(pos, delta);
}

/**
 * \brief Calculates line boundaries of viewport, and then finds
 * the visible sections of code withing those boundaries
 */
std::vector<VisibleSection> LineControl::visibleSectionsForViewport(const QRect &rect) const
{
    if (m_blockHeight < 1 || rect.width() <0 || rect.height() < 0)
        return std::vector<VisibleSection>();


    int firstBlock = qMax(0, qFloor(rect.y()*1.0/m_blockHeight));
    int lastBlock = qCeil((rect.y() + rect.height())*1.0/m_blockHeight);

    return visibleSections(firstBlock, lastBlock);
}

/**
 * \brief Returns visible sections of code within a given range,
 * as a complement of line sections
 */
std::vector<VisibleSection> LineControl::visibleSections(int firstBlock, int lastBlock) const
{    
    std::vector<VisibleSection> result;

    if (m_sections.empty()) {
        // If there's no line sections, the entire range is visible
        result.push_back(VisibleSection(std::min(m_lineNumber - firstBlock, lastBlock - firstBlock + 1), firstBlock));
        return result;
    }

    LineSection ls;
    ls.visiblePosition = firstBlock;

    auto next = std::upper_bound(m_sections.begin(), m_sections.end(), ls, LineSection::compareVisible);
    decltype(next) curr;
    bool noCurr = false;


    // curr is the first section that has curr->visiblePosition <= firstBlock
    if (next != m_sections.begin())
    {
        curr = std::prev(next);
    } else {
        noCurr = true;
    }

    int startPos = firstBlock;

    // The total number of lines that need to be "filled out",
    // so we eiher reach zero, or reach the end of text
    int total = lastBlock - firstBlock + 1;

    while (total > 0)
    {
        // This flag lets us know that we're outside of a line section, which means
        // we're in code, and can use every line until the next line section
        bool aboveCurr = false;
        if (!noCurr)
        {
            switch (curr->type)
            {
            case LineSection::Palette:
                if (startPos < curr->visiblePosition + curr->visibleRange)
                {
                    // Start position is within palette, we're showing the lower part of it
                    int size = curr->visibleRange - (startPos - curr->visiblePosition);
                    result.push_back(VisibleSection(std::min(total, size), curr->position, curr->palette));
                    total -= std::min(total, size);
                    startPos = curr->visiblePosition + curr->visibleRange;
                } else {
                    aboveCurr = true;
                }
                break;

            case LineSection::Collapsed:
                // If we're at the start of collapsed, we only show the first line
                if (startPos == curr->visiblePosition)
                {
                    result.push_back(VisibleSection(1, curr->position));
                    total -= 1;
                    startPos = curr->visiblePosition + 1;
                 } else {
                     aboveCurr = true;
                 }
                break;
            case LineSection::Fragment:
                if (curr->position == 0) {
                    // If we're inside the start fragment, we skip it completely, since it's all hidden
                    aboveCurr = true;
                } else {
                    // If we've reached the end fragment, there's no more lines to add
                    noCurr = false;
                    total = 0; // the end
                }
                break;
            }
        }

        if (noCurr || aboveCurr)
        {
            // This means we're in code, so we can add a visible section until the next line section,
            // or perhaps the end of code
            if (next == m_sections.end())
            {
                int size = std::min(total, m_lineNumber - startPos + curr->positionOffset() + curr->rangeOffset());
                if (size > 0) result.push_back(VisibleSection(std::min(total, m_lineNumber - startPos + curr->positionOffset() + curr->rangeOffset()), startPos - curr->positionOffset() - curr->rangeOffset()));
                total = 0;
            } else {
                int size = std::min(total, next->visiblePosition - startPos);
                if (size > 0)
                {
                    result.push_back(VisibleSection(std::min(total, next->visiblePosition - startPos), startPos - next->positionOffset()));
                    total -= size;
                }
                startPos = next->visiblePosition;

                curr = next;
                next = std::next(next);
                if (noCurr) noCurr = false;
            }
        }
    }

    return result;
}

/**
 * \brief A test function to simulate change of line count
 */
void LineControl::simulateLineCountChange(int delta)
{
    if (delta == 0) return;
    m_prevLineNumber = m_lineNumber;
    m_lineNumber += delta;

    bool internal = false;

    handleLineChange(delta, internal);
}

int LineControl::maxWidth()
{
    return m_maxWidth;
}

/**
 * \brief This function adds the line section to `m_sections`, taking into consideration
 * nesting, as well as generated offsets created by its insertion.
 * \returns Total offset generated by its insertion
 */
int LineControl::addLineSection(LineControl::LineSection ls)
{
    // Find sections whose starting position is larger than the one we're currently inserting.
    auto srch = std::upper_bound(m_sections.begin(), m_sections.end(), ls, LineSection::compare);
    // This variable stores the visual offset (measured in lines) that this operation creates.
    int resultLineOffset = 0;
    std::vector<LineSection> nested;
    // Every section that's contained inside the section being inserted is stored in a `nested` container
    while (srch != m_sections.end()
           && srch->position + srch->range < ls.position+ls.range)
    {
        nested.push_back(*srch);
        srch++;
    }

    // Each nested section needs to be "reverted"
    for (LineSection l: nested)
    {
        if (l.type == LineSection::Collapsed)
        {
            resultLineOffset += removeLineSection(l, false, false);
        }
        else {
            l.palette->setVisible(false);
            resultLineOffset += removeLineSection(l, false, false);
        }
    }

    // If we've inserted a line section that already has nested sections, we include those as well
    for (LineSection l: ls.nested)
    {
        nested.push_back(l);
    }

    ls.nested = nested;


    unsigned elementPos = insertIntoSorted(ls);

    // We calculate the visible (line) position of the newly inserted section
    // based on the offsets from every previous section.
    calculateVisiblePosition(elementPos);

    if (ls.type == LineSection::Palette)
    {
        ls.palette->setProperty("x", 0);
        // This yValue is calculated in a way to center it inside the space given by a `visibleRange` number of lines
        int yValue = m_sections[elementPos].visiblePosition * m_blockHeight + (m_sections[elementPos].visibleRange * m_blockHeight - static_cast<int>(ls.palette->height())) / 2;
        yValue = yValue > 0 ? yValue : 0;
        ls.palette->setProperty("y", yValue);
    }

    if (ls.width > m_maxWidth) m_maxWidth = ls.width;

    // We add the offset generated by this section alone to the resulting offset
    resultLineOffset += m_sections[elementPos].rangeOffset();
    // We also have to update the sections following this one with the offset it has generated
    if (m_sections[elementPos].visibleRange != m_sections[elementPos].range)
        offsetAfterIndex(elementPos, m_sections[elementPos].rangeOffset(), false);

    return resultLineOffset;
}

/**
 * \brief Removes the line section given by its first parameter. If it's a palette, we can optionally
 * destroy it.
 * \returns Line offset created by the execution of this function.
 */
int LineControl::removeLineSection(LineControl::LineSection ls, bool destroy, bool restoreNestedPalettes)
{
    auto lower = std::lower_bound(m_sections.begin(), m_sections.end(), ls, LineSection::compare);
    unsigned index = static_cast<unsigned>(lower-m_sections.begin());
    std::vector<LineSection> nested = lower->nested;
    int result = 0;

    if (lower->type == LineSection::Palette && destroy){
        lower->palette->setVisible(false);
        QMetaObject::invokeMethod(lower->palette, "close", Qt::DirectConnection);
    }

    offsetAfterIndex(index, -m_sections[index].rangeOffset(), false);

    m_sections.erase(lower);

    if (restoreNestedPalettes)
    {
        for (LineSection lsx: nested){
            if (lsx.type == LineSection::Palette){
                lsx.palette->setVisible(true);
            }
            result += addLineSection(lsx);

        }
    }

    return result;
}

int LineControl::LineSection::rangeOffset() const
{
    return visibleRange - range;
}

int LineControl::LineSection::positionOffset() const
{
    return visiblePosition - position;
}

VisibleSection::VisibleSection(int sz, int st, QQuickItem* p):
    size(sz), start(st), palette(p) {}


} // namespace
