# The configuration for projects depending on the lcveditor

QMLJSPARSER_INCLUDE_DIR = $$PATH_SOURCE_EDITOR_QMLJSPARSER/src

!exists($$QMLJSPARSER_INCLUDE_DIR): \
    error($$_FILE_: Could not find $$QMLJSPARSER_INCLUDE_DIR)

LIBS += -L$$PATH_DEPLOY_APPLICATION -lqmljsparser
INCLUDEPATH += $$QMLJSPARSER_INCLUDE_DIR
DEPENDPATH  += $$QMLJSPARSER_INCLUDE_DIR
